print("**********************************************************************")
print("Hello! Welcome to Hide & Seek!")
print("Hide & Seek is a logic-based game built entirely in Python.")
print("**********************************************************************")
player_name = input("Firstly, what is your name?: ")
print("Hi " + player_name + ", let's play Hide & Seek!")